$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  conda:
    type: object
    properties:
      activate:
        type: string
      basic:
        type: string
      python:
        type: string
    required:
      - activate
      - basic
      - python

  database:
    type: object
    properties:
      acc_type:
        type: string
      datasets:
        type: string
      hbvtype:
        type: object
        embl:
          type: object
          additionalProperties:
            type: string
        genome:
          type: object
          additionalProperties:
            type: string
    required:
      - acc_type
      - datasets
      - hbvtype

  samples:
    type: array
    items:
      type: string
    minItems: 1
    uniqueItems: true

  threads:
    type: object
    properties:
      high:
        type: integer
      low:
        type: integer
      max:
        type: integer
    required:
      - high
      - low
      - max

  workdir:
    type: string

required:
  - conda
  - database
  - samples
  - threads
  - workdir
